/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

/**
 *
 * @author x13481152
 */
public class FfieldstudyGUI extends javax.swing.JFrame {

    /**
     * Creates new form fieldstudyGUI
     */
    public FfieldstudyGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        markingschemesbutton = new javax.swing.JButton();
        notesbutton = new javax.swing.JButton();
        exampapersbutton = new javax.swing.JButton();
        Quizzesbutton = new javax.swing.JButton();
        FSreturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Field Study");

        markingschemesbutton.setBackground(new java.awt.Color(51, 153, 255));
        markingschemesbutton.setText("Making Schemes");
        markingschemesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemesbuttonActionPerformed(evt);
            }
        });

        notesbutton.setBackground(new java.awt.Color(51, 153, 255));
        notesbutton.setText("Notes");
        notesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesbuttonActionPerformed(evt);
            }
        });

        exampapersbutton.setBackground(new java.awt.Color(51, 153, 255));
        exampapersbutton.setText("Exam Papers");
        exampapersbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exampapersbuttonActionPerformed(evt);
            }
        });

        Quizzesbutton.setBackground(new java.awt.Color(51, 153, 255));
        Quizzesbutton.setText("Quizzes");
        Quizzesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizzesbuttonActionPerformed(evt);
            }
        });

        FSreturn.setText("Back");
        FSreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FSreturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(markingschemesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exampapersbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quizzesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FSreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FSreturn)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markingschemesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exampapersbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quizzesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void markingschemesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemesbuttonActionPerformed
        // TODO add your handling code here:
        FMarkingSchemesGUI n = new FMarkingSchemesGUI();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_markingschemesbuttonActionPerformed

    private void exampapersbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exampapersbuttonActionPerformed
        FExamPapersGUI ep = new FExamPapersGUI();
        ep.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_exampapersbuttonActionPerformed

    private void QuizzesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizzesbuttonActionPerformed
        // TODO add your handling code here:
        FQuizDirectoryGUI QD = new FQuizDirectoryGUI();
        QD.setVisible(true);
        dispose();
    }//GEN-LAST:event_QuizzesbuttonActionPerformed

    private void notesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesbuttonActionPerformed
        // TODO add your handling code here:
        FNotesGUI wu = new FNotesGUI();
        wu.setVisible(true);
        dispose();

    }//GEN-LAST:event_notesbuttonActionPerformed

    private void FSreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FSreturnActionPerformed
        MainMenu myMainMenu = new MainMenu();
        myMainMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_FSreturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FfieldstudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FfieldstudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FfieldstudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FfieldstudyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FSreturn;
    private javax.swing.JButton Quizzesbutton;
    private javax.swing.JButton exampapersbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton markingschemesbutton;
    private javax.swing.JButton notesbutton;
    // End of variables declaration//GEN-END:variables
}
