/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Biology;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author x13481152
 */
public class FMarkingSchemesGUI extends javax.swing.JFrame {

    /**
     * Creates new form notesGUI
     */
    public FMarkingSchemesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        markingschemelabel = new javax.swing.JLabel();
        markingschemesreturnbutton = new javax.swing.JButton();
        markingschemes2014button = new javax.swing.JButton();
        markingschemes2012button = new javax.swing.JButton();
        markingschemes2011button = new javax.swing.JButton();
        markingschemes2009button = new javax.swing.JButton();
        markingschemes2013button = new javax.swing.JButton();
        markingschemes2010button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        markingschemelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        markingschemelabel.setText("Marking Schemes");

        markingschemesreturnbutton.setText("Back");
        markingschemesreturnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemesreturnbuttonActionPerformed(evt);
            }
        });

        markingschemes2014button.setBackground(new java.awt.Color(51, 153, 255));
        markingschemes2014button.setText("2014");
        markingschemes2014button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemes2014buttonActionPerformed(evt);
            }
        });

        markingschemes2012button.setBackground(new java.awt.Color(51, 153, 255));
        markingschemes2012button.setText("2012");
        markingschemes2012button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemes2012buttonActionPerformed(evt);
            }
        });

        markingschemes2011button.setBackground(new java.awt.Color(51, 153, 255));
        markingschemes2011button.setText("2011");
        markingschemes2011button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemes2011buttonActionPerformed(evt);
            }
        });

        markingschemes2009button.setBackground(new java.awt.Color(51, 153, 255));
        markingschemes2009button.setText("2009");
        markingschemes2009button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemes2009buttonActionPerformed(evt);
            }
        });

        markingschemes2013button.setBackground(new java.awt.Color(51, 153, 255));
        markingschemes2013button.setText("2013");
        markingschemes2013button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemes2013buttonActionPerformed(evt);
            }
        });

        markingschemes2010button.setBackground(new java.awt.Color(51, 153, 255));
        markingschemes2010button.setText("2010");
        markingschemes2010button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markingschemes2010buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(markingschemesreturnbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(markingschemelabel)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(markingschemes2014button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(markingschemes2011button, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(markingschemes2010button, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(markingschemes2013button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(markingschemes2012button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(markingschemes2009button, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markingschemelabel)
                    .addComponent(markingschemesreturnbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(markingschemes2014button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markingschemes2013button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markingschemes2012button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(markingschemes2009button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markingschemes2010button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(markingschemes2011button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void markingschemesreturnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemesreturnbuttonActionPerformed

        FfieldstudyGUI fs = new FfieldstudyGUI();
        fs.setVisible(true); 
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_markingschemesreturnbuttonActionPerformed

    private void markingschemes2014buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemes2014buttonActionPerformed
                                       
        try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2014/LC025ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_markingschemes2014buttonActionPerformed

    private void markingschemes2013buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemes2013buttonActionPerformed
try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2013/LC025ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }             // TODO add your handling code here:
    }//GEN-LAST:event_markingschemes2013buttonActionPerformed

    private void markingschemes2012buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemes2012buttonActionPerformed
try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2012/LC025ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }             // TODO add your handling code here:
    }//GEN-LAST:event_markingschemes2012buttonActionPerformed

    private void markingschemes2011buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemes2011buttonActionPerformed
try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2011/LC025ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }             // TODO add your handling code here:
    }//GEN-LAST:event_markingschemes2011buttonActionPerformed

    private void markingschemes2010buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemes2010buttonActionPerformed
try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2010/LC025ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }             // TODO add your handling code here:
    }//GEN-LAST:event_markingschemes2010buttonActionPerformed

    private void markingschemes2009buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markingschemes2009buttonActionPerformed
try 
        {
            Desktop.getDesktop().browse(new URL("http://www.examinations.ie/archive/markingschemes/2009/LC025ALP000EV.pdf").toURI());
        }           
        catch (URISyntaxException | IOException e) {
        }             // TODO add your handling code here:
    }//GEN-LAST:event_markingschemes2009buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMarkingSchemesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMarkingSchemesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMarkingSchemesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMarkingSchemesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel markingschemelabel;
    private javax.swing.JButton markingschemes2009button;
    private javax.swing.JButton markingschemes2010button;
    private javax.swing.JButton markingschemes2011button;
    private javax.swing.JButton markingschemes2012button;
    private javax.swing.JButton markingschemes2013button;
    private javax.swing.JButton markingschemes2014button;
    private javax.swing.JButton markingschemesreturnbutton;
    // End of variables declaration//GEN-END:variables
}
