/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author x13481152
 */

public class FQuiz2 extends javax.swing.JFrame {

    private final ArrayList<String> answers;
    private final ArrayList<String> questions;
    private int count;

    /**
     * Creates new form FQuiz1
     */
    public FQuiz2() {
        initComponents();
        answers = new ArrayList<>();
        questions = new ArrayList<>();

        String q1 = "What is the colour is grass";
        String q2 = "What is the colour of the sky?";
        String q3 = "What do bees collect?";
        String q4 = "What do they make with it?";
        String q5 = "What word starts with photo and ends with synthesis";

        String a1 = "green";
        String a2 = "blue";
        String a3 = "pollen";
        String a4 = "honey";
        String a5 = "photosynthesis";

        questions.add(q1);
        questions.add(q2);
        questions.add(q3);
        questions.add(q4);
        questions.add(q5);

        answers.add(a1);
        answers.add(a2);
        answers.add(a3);
        answers.add(a4);
        answers.add(a5);

        count = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quiz1label = new javax.swing.JLabel();
        preparedbutton = new javax.swing.JButton();
        nobutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Quiz1label.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Quiz1label.setText("Quiz 2");

        preparedbutton.setBackground(new java.awt.Color(51, 153, 255));
        preparedbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        preparedbutton.setText("I am prepared");
        preparedbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preparedbuttonActionPerformed(evt);
            }
        });

        nobutton.setBackground(new java.awt.Color(51, 153, 255));
        nobutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nobutton.setText("No, I can't handle it!");
        nobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Prepare yourself!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(preparedbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nobutton)
                .addGap(0, 97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(Quiz1label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Quiz1label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preparedbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preparedbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preparedbuttonActionPerformed
        // TODO add your handling code here
        while (count <= answers.size()) {

            String inAnswer = JOptionPane.showInputDialog(null, questions.get(count));

            if (inAnswer.equals(answers.get(count))) {
                JOptionPane.showMessageDialog(null, "Correct");
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect");
            }
            count++;

        }


    }//GEN-LAST:event_preparedbuttonActionPerformed

    private void nobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobuttonActionPerformed
        FQuizDirectoryGUI myFQuizDirectoryGUI = new FQuizDirectoryGUI();
        myFQuizDirectoryGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_nobuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FQuiz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quiz1label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nobutton;
    private javax.swing.JButton preparedbutton;
    // End of variables declaration//GEN-END:variables
}
