/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Biology;

/**
 *
 * @author x13481152
 */
public class FQuizDirectoryGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizDirectoryGUI
     */
    public FQuizDirectoryGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quiz1button = new javax.swing.JButton();
        Quiz2button = new javax.swing.JButton();
        Quiz3button = new javax.swing.JButton();
        notesReturnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Quiz1button.setBackground(new java.awt.Color(51, 153, 255));
        Quiz1button.setText("Quiz 1");
        Quiz1button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quiz1buttonActionPerformed(evt);
            }
        });

        Quiz2button.setBackground(new java.awt.Color(51, 153, 255));
        Quiz2button.setText("Quiz 2");
        Quiz2button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quiz2buttonActionPerformed(evt);
            }
        });

        Quiz3button.setBackground(new java.awt.Color(51, 153, 255));
        Quiz3button.setText("Quiz 3");
        Quiz3button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quiz3buttonActionPerformed(evt);
            }
        });

        notesReturnButton.setText("Back");
        notesReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesReturnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(notesReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quiz1button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quiz3button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quiz2button, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quiz1button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notesReturnButton))
                .addGap(18, 18, 18)
                .addComponent(Quiz2button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Quiz3button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //declare buttons
    //Quiz1 button
    private void Quiz1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quiz1buttonActionPerformed
        // TODO add your handling code here:
        FQuiz1 Q1 = new FQuiz1();
        Q1.setVisible(true); 
        dispose();
    }//GEN-LAST:event_Quiz1buttonActionPerformed
    
    //Quiz2 button
    private void Quiz2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quiz2buttonActionPerformed
        // TODO add your handling code here:
        FQuiz2 Q2 = new FQuiz2();
        Q2.setVisible(true); 
        dispose();
    }//GEN-LAST:event_Quiz2buttonActionPerformed

    //return button
    private void notesReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesReturnButtonActionPerformed
FfieldstudyGUI fs = new FfieldstudyGUI();
        fs.setVisible(true); 
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_notesReturnButtonActionPerformed

    //Quiz3 button
    private void Quiz3buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quiz3buttonActionPerformed
        // TODO add your handling code here:
        FQuiz3 Q3 = new FQuiz3();
        Q3.setVisible(true); 
        dispose();
    }//GEN-LAST:event_Quiz3buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FQuizDirectoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FQuizDirectoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FQuizDirectoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FQuizDirectoryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Quiz1button;
    private javax.swing.JButton Quiz2button;
    private javax.swing.JButton Quiz3button;
    private javax.swing.JButton notesReturnButton;
    // End of variables declaration//GEN-END:variables
}
