/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author karry
 */
public class OOrgQuiz extends javax.swing.JFrame {
        
    private ArrayList <OResults> arResults;
    private String Q1ans;
    private String Q2ans;
    private String Q3ans;
    private String Q4ans;
    private int count;
    private String Q1res;
    private String Q2res;
    private String Q3res;
    private String Q4res;
    /**
     * Creates new form OrgQuiz
     */
    public OOrgQuiz() {
        initComponents();
        
        arResults = new ArrayList <>();
        Q1ans = new String();
        Q2ans = new String();
        Q3ans = new String();
        Q4ans = new String();
        count = 0;
        Q1res = " ";
        Q2res = " ";
        Q3res = " ";
        Q4res = " ";
    }
      
   
    /*  p = new JPanel();   // create panel
    p.setLayout(null);  // set layout to null in jpanel
    p.setBackground(Color.green); //set background of panel
    add(p);//add jpanel to jframe */
    
      
   private void writeObjectToFile() throws IOException{
        try{
            
            //Setting up a file object
        
            File f = new File("output.txt");
            FileWriter fw = new FileWriter(f);
            BufferedWriter mWriter = new BufferedWriter(fw);
            
            mWriter.write("Writing to file"); //Writing a line feed to the file
            mWriter.close();    //closing file stream
            
    } catch (IOException e){
        System.out.println(e.toString());
        System.out.println("There was a proglem with writing to the File");
        }
       
    }
    private void readObjectFromFile(){
    try{
        File f = new File("input.txt");
        FileReader fr = new FileReader(f);
        BufferedReader mReader = new BufferedReader(fr);

        String line = mReader.readLine();
        while (line != null) {
            line = mReader.readLine();
        }
        mReader.close();

} catch (IOException e){
        System.out.println(e.toString());
        System.out.println("There is a problem with writting to this File");
}
    }

   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headtxt = new javax.swing.JLabel();
        bckbtn = new javax.swing.JButton();
        Q1 = new javax.swing.JLabel();
        Q1ansTf = new javax.swing.JTextField();
        Q2 = new javax.swing.JLabel();
        Q2ansTf = new javax.swing.JTextField();
        Q3 = new javax.swing.JLabel();
        Q3ansTf = new javax.swing.JTextField();
        Q4 = new javax.swing.JLabel();
        Q4ansTf = new javax.swing.JTextField();
        deletebtn = new javax.swing.JButton();
        displaybtn = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headtxt.setText("Quiz");

        bckbtn.setText("Back");
        bckbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckbtnActionPerformed(evt);
            }
        });

        Q1.setText("Question 1:What are the Five Kingdoms of Diversity in Organism? ");

        Q1ansTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1ansTfActionPerformed(evt);
            }
        });

        Q2.setText("Question 2: Which of the Kingdoms classify as Fungi? ");

        Q2ansTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2ansTfActionPerformed(evt);
            }
        });

        Q3.setText("Question 3: What is evolusion? Explain with examples. ");

        Q3ansTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3ansTfActionPerformed(evt);
            }
        });

        Q4.setText("Question 4: Differenciate between food chain and food web, Give examples. ");

        Q4ansTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4ansTfActionPerformed(evt);
            }
        });

        deletebtn.setBackground(new java.awt.Color(102, 204, 0));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        displaybtn.setBackground(new java.awt.Color(102, 204, 0));
        displaybtn.setText("Display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });

        submit1.setBackground(new java.awt.Color(102, 204, 0));
        submit1.setText("Submit");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        searchbtn.setBackground(new java.awt.Color(102, 204, 0));
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Q1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bckbtn)
                                .addGap(86, 86, 86)
                                .addComponent(headtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Q1ansTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Q2ansTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q3ansTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Q4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Q4ansTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchbtn)
                                .addGap(14, 14, 14)
                                .addComponent(deletebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(displaybtn)
                                .addGap(72, 72, 72)
                                .addComponent(submit1)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bckbtn)
                    .addComponent(headtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q1ansTf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Q2ansTf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q3ansTf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Q4ansTf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(submit1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displaybtn)
                            .addComponent(deletebtn)
                            .addComponent(searchbtn))
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Q1ansTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1ansTfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Q1ansTfActionPerformed

    private void Q3ansTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3ansTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q3ansTfActionPerformed

    private void Q4ansTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4ansTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q4ansTfActionPerformed

    private void bckbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckbtnActionPerformed
        // TODO add your handling code here:
        OGUI myOrganism = new OGUI();
        myOrganism.setVisible(true);
        dispose();
    }//GEN-LAST:event_bckbtnActionPerformed

    private void Q2ansTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2ansTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q2ansTfActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        // TODO add your handling code here:
        Q1ans = Q1ansTf.getText();
        Q2ans = Q2ansTf.getText();
        Q3ans = Q3ansTf.getText();
        Q4ans = Q4ansTf.getText();
        
         if (Q1ans.equalsIgnoreCase("monera, protista,fungi, plantae, animalia")){
            Q1res = "Correct!";
        }
         else{ 
             Q1res = "Wrong Answer!";
         }
         
          if (Q2ans.equalsIgnoreCase("mushrooms")){
            Q2res = "Correct!";
        }
         else{ 
             Q2res = "Wrong Answer!";
         }
          
           if (Q3ans.equalsIgnoreCase("genetic change in population. genes passed on. ")){
            Q3res = "Correct!";
        }
         else{ 
             Q3res = "Wrong Answer!";
         }
        
            if (Q4ans.equalsIgnoreCase("food chain: feeding hierarchy where organisms in ecosystem are grouped.\n" +
"	food web: many food chains linked together to show feeding relationships of ecosystem.")){
            Q4res = "Correct!";
        }
         else{ 
             Q4res = "Wrong Answer!";
         }
         
         
         OResults myResults = new OResults();
         myResults.setQ1ans(Q1ans);
         myResults.setQ1res(Q1res);
         myResults.setQ2ans(Q2ans);
         myResults.setQ2res(Q2res);
         myResults.setQ3ans(Q3ans);
         myResults.setQ3res(Q3res);
         myResults.setQ4ans(Q4ans);
         myResults.setQ4res(Q4res);
         
         arResults.add(myResults);
         
         count++;
         
    }//GEN-LAST:event_submit1ActionPerformed

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i< arResults.size();i++){
            JOptionPane.showMessageDialog(null, "Question 1: "+ arResults.get(i).getQ1ans()+"\n Question 1 result: "+ arResults.get(i).getQ1res()+ "\n Question 2: "+ arResults.get(i).getQ2ans()+"\n Question 2 result: "+ arResults.get(i).getQ2res()+"\n Question 3: "+ arResults.get(i).getQ3ans()+"\n Question 3 result: "+ arResults.get(i).getQ3res()+"\n Question 4: "+ arResults.get(i).getQ4ans()+"\n Question 4 result: "+ arResults.get(i).getQ4res());
        }
    }//GEN-LAST:event_displaybtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        try{
            String URL = "https://www.google.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        
        catch(Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:

          /*if(Q3res.getText().equals("")&&!Q2res.getText().equals("")&& Q1res.getText().equals("")&&!Q4res.getText().equals("")){
              JOptionPane.showMessageDialog(null,"please enter an answer again");
            }
            else if(count ==0){
            JOptionPane.showMessageDialog(null,"Sorry this input was incorrect");
            }
            else{
                Q1res  = Q1res.getText();
                Q2res = Q2res.getText();
                Q3res = Q3res.getText();
                Q4res = Q4res.getText();
            }

            for(int i = 0; i < arResults.size(); i++){
            if(arResults[i].getQ1res().equals(Q1res)&& arResults[i].getQ2res().equals(Q2res)&&arResults[i].getQ3res().equals(Q3res)&&arResults[i].getQ4res().equals(Q4res)){
            arResults.remove(i);
            count = count - 1;
            JOptionPane.showMessageDialog(null, "Delete: "+Q1res+"," +Q2res+","+Q3res+","+Q4res+"from the array. There are now" +count+"  question answers in the array.");
            break;
            }
            if(i==count-1){
            JOptionPane.showMessageDialog(null,"Sorry this input is not available");
            
            }
        }
            
    }
                   for(int i = 0; i < count; i = i +1){
              if(arResults.get(i).getQ1res().equals(Q1res)&& arResults.get(i).getQ2res().equals(Q2res)&&arResults.get(i).getQ3res().equals(Q3res)&&arResults.get(i).getQ4res().equals(Q4res)){
                  arResults.set(i, arResults.get(count-1));
                  count = count - 1;
                  JOptionPane.showMessageDialog(null, "Delete: "+Q1res+"," +Q2res+","+Q3res+","+Q4res+"from the array. There are now" +count+"  question answers in the array.");
                  break;
              }
              if(i==count-1){
                  JOptionPane.showMessageDialog(null,"Sorry this input is not available");
                  
              }           
          }

    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OOrgQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OOrgQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OOrgQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OOrgQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OOrgQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Q1;
    private javax.swing.JTextField Q1ansTf;
    private javax.swing.JLabel Q2;
    private javax.swing.JTextField Q2ansTf;
    private javax.swing.JLabel Q3;
    private javax.swing.JTextField Q3ansTf;
    private javax.swing.JLabel Q4;
    private javax.swing.JTextField Q4ansTf;
    private javax.swing.JButton bckbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton displaybtn;
    private javax.swing.JLabel headtxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton submit1;
    // End of variables declaration//GEN-END:variables
}
