/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

/**
 *
 * @author karry
 */
public class OOrgNotes extends javax.swing.JFrame {

    /**
     * Creates new form OrgNotes
     */
    public OOrgNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textlabel = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        kingdoms = new javax.swing.JButton();
        bck = new javax.swing.JButton();
        fung = new javax.swing.JButton();
        virus = new javax.swing.JButton();
        amoe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textlabel.setBackground(new java.awt.Color(255, 255, 255));
        textlabel.setText("          Notes");
        textlabel.setOpaque(true);

        backbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        kingdoms.setBackground(new java.awt.Color(102, 204, 0));
        kingdoms.setText("5 Kingdoms");
        kingdoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kingdomsActionPerformed(evt);
            }
        });

        bck.setBackground(new java.awt.Color(102, 204, 0));
        bck.setText("Bacteria");
        bck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bckActionPerformed(evt);
            }
        });

        fung.setBackground(new java.awt.Color(102, 204, 0));
        fung.setText("Fungi");
        fung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fungActionPerformed(evt);
            }
        });

        virus.setBackground(new java.awt.Color(102, 204, 0));
        virus.setText("Viruses");
        virus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virusActionPerformed(evt);
            }
        });

        amoe.setBackground(new java.awt.Color(102, 204, 0));
        amoe.setText("Amoeba");
        amoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amoeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addGap(44, 44, 44)
                        .addComponent(textlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kingdoms)
                                .addGap(18, 18, 18)
                                .addComponent(bck))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(virus)
                                .addGap(18, 18, 18)
                                .addComponent(amoe)))
                        .addGap(30, 30, 30)
                        .addComponent(fung)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(textlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kingdoms)
                    .addComponent(bck)
                    .addComponent(fung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(virus)
                    .addComponent(amoe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
         OGUI myOrganism = new OGUI();
        myOrganism.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void kingdomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kingdomsActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("Classification  \n" +
"\n" +
"The great diversity of living organisms is organised into groups that share important biological characteristics such as structure.\n" +
"\n" +
"The evolutionary connection between organisms becomes clear by this method of classification.\n" +
"\n" +
"\n" +
"The Five Kingdoms\n" +
"\n" +
"Monera (Prokaryotae)\n" +
"Protista (Protoctista)\n" +
"Fungi\n" +
"Plantae\n" +
"Animalia\n" +
"Kingdom Monera\n" +
"\n" +
"All the prokaryotic organisms are in this Kingdom.\n" +
"Cells do not have a membrane bound nucleus.\n" +
"Cells do not have mitochondria.\n" +
"Chloroplasts are never present.\n" +
"All are unicellular and microscopic.\n" +
"Common Name: Bacteria.\n" +
"Kingdom Protista\n" +
"\n" +
"The eukaryotic organisms that are not fungi, plants or animals are placed in this kingdom.\n" +
"Protists include unicellular, colonial and simple multicellular eukaryotes.\n" +
"Members include the protozoa, algae and moulds.\n" +
"Amoeba is a protist.\n" +
"Kingdom Fungi\n" +
"\n" +
"The fungi are heterotrophic eukaryotes with cell walls of chitin.\n" +
"The hypha, a tubular filament, is the basic unit of organisation of many fungi.\n" +
"The total mass of hyphae is called the mycelium.\n" +
"Yeast, moulds and mushrooms are fungi.\n" +
"Kingdom Plantae\n" +
"\n" +
"The eukaryotic organisms with cell walls of cellulose are plants.\n" +
"All are multicellular photosynthetic autotrophs.\n" +
"Plants show a high degree of structural differentiation.\n" +
"The flowering plants are the most evolved members of this kingdom.\n" +
"Mosses, ferns and conifers also belong to this kingdom.\n" +
"Kingdom Animalia\n" +
"\n" +
"Multicellular, heterotrophic, eukaryotic and cells without a surrounding wall.\n" +
"Therefore our species belongs to the Kingdom Animalia.\n" +
"\n" +
"Flowering Plants  \n" +
"\n" +
"Flowers hold the sexual organs of flowering plants.\n" +
"Flowering plants reproduce sexually by forming seeds in a mature ovary (fruit).\n" +
"Flowering plants have specialised vascular tissue (xylem, phloem).\n" +
"The flowering plants are divided into two classes, monocotyledons and dicotyledons.\n" +
"\n" +
"Monocots and Dicots  \n" +
"\n" +
"Monocoyledons\n" +
"\n" +
"Plant embryo has one leaf (cotyledon – seed leaf).\n" +
"Foliage leaves have parallel veins.\n" +
"Vascular bundles of the stem are scattered or arranged in two or more rings.\n" +
"Flower parts in three or multiples of three.\n" +
"90% are herbaceous (non-woody).\n" +
"Examples: grass, onion.\n" +
"Dicotyledons\n" +
"\n" +
"Plant embryo has two leaves.\n" +
"Foliage leaves have branching veins.\n" +
"Vascular bundles of the stem are in one ring.\n" +
"Flower parts in four or five.\n" +
"Approximately 50% are herbaceous and 50% woody.\n" +
"Examples: buttercup, pea, oak, ash.");
    }//GEN-LAST:event_kingdomsActionPerformed

    private void bckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bckActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("Bacteria\n" +
"\n" +
"Classification: unicellular prokaryotes of the Kingdom Monera.\n" +
"\n" +
"Distribution: ubiquitous – found everywhere in the biosphere.\n" +
"\n" +
"Textbook Diagram: the three major shapes of bacterial cells – spherical, rod, spiral.\n" +
"\n" +
"Textbook Diagram: detailed structure of bacterium cell.\n" +
"\n" +
"\n" +
"Structure of Bacterium Cell\n" +
"\n" +
"Size: about 1,000 smaller than a human cell.\n" +
"\n" +
"Cell Wall: non-cellulose, supports, gives shape to and protects the cell from bursting when turgid.\n" +
"\n" +
"Capsule: protection against other micro-organisms and host defences; attachment to solid surfaces.\n" +
"\n" +
"Flagellum: locomotion.\n" +
"\n" +
"Genetic Material: single circular DNA molecule with very little attached protein (not a true chromosome), not surrounded by a membrane so not a true nucleus.\n" +
"\n" +
"Plasmid: small circular DNA – may be one or many present, replicates independently of ‘bacterial chromosome’, may contain genes of use to the bacterium e.g. antibiotic resistance, easily taken up from external environment or transferred from other bacteria.\n" +
"\n" +
"\n" +
"Reproduction \n" +
"\n" +
"Method: asexual by binary fission.\n" +
"\n" +
"Textbook Diagram: sequence showing binary fission.\n" +
"\n" +
"Bacterium cell is growing.\n" +
"DNA replicates.\n" +
"DNA copies separate as bacterium cell grows.\n" +
"Cross wall forms, between the identical DNA copies, by ingrowth of cell membrane and cell wall.\n" +
"Two identical daughter cells formed.\n" +
"Speed: 20 minutes – more than one billion bacteria after 30 generations in 10 hours.\n" +
"\n" +
"Favourable mutations become established in bacterial populations.\n" +
"\n" +
"Bacterial populations can evolve very rapidly in response to changes in environmental conditions.\n" +
"\n" +
"\n" +
"Endospores \n" +
"\n" +
"Some bacteria form resistant endospores at the onset of extremely unfavourable environmental conditions.\n" +
"\n" +
"Growth stops, tough wall forms around the dry shrunken cytoplasm, cell ruptures releasing the endospore.\n" +
"\n" +
"Converts back rapidly to a vegetative bacterial cell when favourable growth conditions return.\n" +
"\n" +
"\n" +
"Nutrition \n" +
"\n" +
"Autotrophic: capable of making their own food from inorganic materials.\n" +
"Photosynthetic: light energy is used to make carbohydrate from carbon dioxide; e.g. green sulphur bacteria.\n" +
"Chemosynthetic: energy for carbohydrate formation is obtained from chemical reactions;\n" +
"nitrifying bacteria.\n" +
"Heterotrophic: not able to make their own food from inorganic materials.\n" +
"Saprophytic: feed on dead organic matter e.g. bacteria of decay, psueudomonas.\n" +
"Parasitic: live with and feed off another living organism causing it harm e.g. cholera bacterium.\n" +
"Mutualistic: lives with another living organism from which it receives food but contribute positivel to their partner e.g. symbiotic nitrogen-fixing bacteria in the roots of clover and beans.\n" +
"\n" +
"Growth Factors\n" +
"Temperature: affects the rate of enzyme action and excessive heat denatures the enzymes.\n" +
"Oxygen Concentration\n" +
"Aerobes: capable of using and growing in air at normal, 21%, oxygen concentration.\n" +
"Microaerophiles: can survive and use free oxygen but only in low concentration.\n" +
"Anaerobes: cannot use free oxygen for respiration.\n" +
"Obligate Anaerobes are killed by free oxygen.\n" +
"Aerotolerant Anaerobes: can survive free oxygen but cannot use it.\n" +
"pH: affects the rate of enzyme action; pH wide of optimum denatures the enzymes.\n" +
"External Solute Concentration\n" +
"High external concentration will cause bacteria to lose water by osmosis slowing or halting metabolism resulting in death and in some will stimulate endospore formation. The cytoplasm of bacteria is usually at a higher concentration than the external environment so water will tend to move into the bacteria by osmosis.\n" +
"\n" +
"Pressure\n" +
"Pressure lowers the melting point, raises the boiling point and alters the solvent ability of water. Each type of bacterium operates best at the pressure of the ecosystem it evolved in.\n" +
"\n" +
"\n" +
"Growth Curves\n" +
"Batch Processing\n" +
"\n" +
"Textbook Diagram: growth curve of five stages.\n" +
"\n" +
"Lag Phase: low multiplication rate, bacteria adapting to the new nutrient environment.\n" +
"Log Phase: rapid metabolism, favourable environmental conditions, fast reproduction.\n" +
"Stationary Phase: ‘birth’ and ‘death’ rates are equal; growth and reproduction has slowed due to build up of toxins and/or increased competition for nutrients, oxygen, space.\n" +
"Decline Phase: death rate is greater than reproduction rate; conditions deteriorating.\n" +
"Death or Survival: bacteria die or survive by going dormant or forming endospores.\n" +
"Continuous Flow Processing\n" +
"\n" +
"Textbook Diagram: growth curve graph – constant favourable rate of product formation.\n" +
"\n" +
"Constant supply of nutrient into the bioreactor at optimum conditions.\n" +
"Constant removal of culture rich in the product and low in contamination.\n" +
"Beneficial Bacteria (any two)\n" +
"Medical: production of antibiotics, hormone and vaccines.\n" +
"Food Production: cheese, yoghurt, vinegar.\n" +
"Our Health: mutualistic bacteria in our large intestine – vitamins B and D.\n" +
"Pollution Control: sewage treatment, bioremediation of polluted environments.\n" +
"Harmful Bacteria (any two)\n" +
"\n" +
"Tooth Decay\n" +
"Food Spoilage\n" +
"Human Diseases: tuberculosis, pneumonia, cholera, whooping cough, ulcers, tetanus.\n" +
"Agriculture: livestock and crop diseases.\n" +
"A pathogen is a disease causing organism.\n" +
"\n" +
"Pathogenic bacteria cause harm to the host organism they have invaded and are growing within.\n" +
"\n" +
"\n" +
"Antibiotics \n" +
"\n" +
"An antibiotic is a chemical substance produced by bacteria or fungi that inhibit the growth of other bacteria or fungi.\n" +
"\n" +
"The natural role of antibiotics is to inhibit the growth of competing micro-organisms.\n" +
"\n" +
"Antibiotics used in medicine are harmful to the infectious bacterium/fungus but relatively harmless to us.\n" +
"\n" +
"Abuse of Antibiotics in Medicine (3P)\n" +
"\n" +
"Poor Patient Practice: patients stop their course of antibiotics when they feel better – it is essential to complete the course to reduce the risk of antibiotic resistant stains of pathogens developing.\n" +
"Poor Prescribing Practice: the use of antibiotics for viral infections or as a placebo; antibiotics are ineffective against viruses.\n" +
"Acquired Resistance to Antibiotics\n" +
"Initially a type of bacteria may be sensitive to a particular antibiotic.\n" +
"The bacteria can become resistant if the antibiotic becomes a normal factor in its environment.\n" +
"Resistance to the antibiotic can be acquired by mutation or uptake of genes from plasmids, viruses or from other resistant bacteria.\n" +
"Antibiotic resistant strains have the advantage over antibiotic sensitive strains in environments where antibiotics are a constant factor.");
    }//GEN-LAST:event_bckActionPerformed

    private void fungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fungActionPerformed
        // TODO add your handling code here:
                jTextArea1.setText("Fungi\n" +
"\n" +
"Characteristics: eukaryotic, heterotrophic, cell wall of chitin.\n" +
"\n" +
"Distribution: mostly terrestrial, living in soil; some can be found in freshwater and a few are marine.\n" +
"Nutrition\n" +
"\n" +
"Saprophytic: feed on dead organic matter e.g. Rhizopus.\n" +
"Parasitic: live with and feed off another living organism causing it harm, e.g., potato blight fungus.\n" +
"\n" +
"Rhizopus  \n" +
"\n" +
"Vegetative Structure\n" +
"Textbook Diagram: vegetative structure.\n" +
"\n" +
"Hypha: a tubular filament growing at its tip, new hyphae form by branching.\n" +
"Mycelium: all the hyphae together making up the vegetative mass of the fungus.\n" +
"Stolon Hyphae: horizontal hyphae growing across and colonising the food environment.\n" +
"Rhizoidal Hyphae: penetrate the solid medium anchoring the fungus.\n" +
"Sporangium: a vessel in which the spores are formed and are released for wind dispersal.\n" +
"Sporangiophore: a hypha carrying a sporangium.\n" +
"Columnella: a cross wall separating the spores from the sporangiophore, aids spore release.\n" +
"Apophysis: a swelling beneath the sporangium.\n" +
"Spores: unicellular asexual reproductive and dispersal agents.\n" +
"Mode of Nutrition\n" +
"Hyphae secrete digestive enzymes into the external environment.\n" +
"External digestion of complex biomolecules.\n" +
"Absorption of the simple soluble products of digestion by diffusion and active transport.\n" +
"Distribution of absorbed nutrients through the mycelium.\n" +
"Reproduction and Life Cycle of Rhizopus\n" +
"\n" +
"Asexual Reproduction\n" +
"\n" +
"Vegetative structure is haploid (n).\n" +
"Sporangia form at the tip of sporangiophores.\n" +
"The sporangium fills with haploid nuclei and cytoplasm.\n" +
"The columnella forms separating the sporangium from the sporangiophore.\n" +
"Each nucleus with cytoplasm forms a haploid spore with a tough resistant wall.\n" +
"The spores are wind dispersed.\n" +
"The spores germinate forming a new haploid mycelium if conditions are suitable.\n" +
"Sexual Reproduction\n" +
"Textbook Diagram: sexual reproduction by Rhizopus.\n" +
"\n" +
"Mycelia of opposite strain are close.\n" +
"Hyphae of opposite strain grow towards each other.\n" +
"The touching tips of the hyphae fill with nuclei and cytoplasm – progametangia formed.\n" +
"A cross wall forms behind each tip forming gametangia.\n" +
"The hypha behind each gametangium is called a suspensor.\n" +
"The contents of the gametangia mix.\n" +
"The nuclei of opposite strains fuse in pairs – fertilisation.\n" +
"The combined gametangia develop into a diploid zygospore.\n" +
"The zygospore is thick-walled resistant and dormant.\n" +
"In favourable conditions the zygospore germinates by meiosis.\n" +
"A haploid sporangiophore with a spore-filled sporangium grows from the zygospore.\n" +
"The spores are wind dispersed and germinate forming a new haploid mycelim.\n" +
"\n" +
"Yeast – a unicellular fungus\n" +
"\n" +
"Textbook Diagram: the yeast cell.\n" +
"\n" +
"Reproduction\n" +
"Textbook Diagram: budding of yeast.\n" +
"\n" +
"Asexual reproduction by budding.\n" +
"Good growth conditions – cell increasing in size.\n" +
"A small bubble-like extension grows from the cell.\n" +
"The nucleus undergoes mitosis.\n" +
"A daughter nucleus moves into the bud.\n" +
"The bud may remain attached and form a small colony by further budding.\n" +
"The bud may detach and undergo budding.\n" +
"Budding is a very fast method of reproduction.\n" +
"\n" +
"Economic Importance of Fungi\n" +
"\n" +
"Beneficial\n" +
"\n" +
"Alcohol (ethanol) formation for beer, wine and spirits.\n" +
"Carbon dioxide gas formation for baking and fizzy drinks.\n" +
"Harmful\n" +
"Crop diseases, e.g., potato blight.\n" +
"Food spoilage.\n" +
"\n" +
"Edible and Poisonous Fungi\n" +
"\n" +
"What are commonly called mushrooms and toadstools are the reproductive organs of certain fungi.\n" +
"Scientifically there is no difference between mushrooms and toadstools.\n" +
"There are no features that distinguish edible from poisonous fungi.\n" +
"The ability to recognise the handful of deadly types is essential.\n" +
"Identification of the good edible types is a safe starting point.\n" +
"Edible Examples: Field Mushroom, Parasol Mushroom.\n" +
"Poisonous Examples: Death Cap, Fly Agaric.\n" +
"\n" +
"Mandatory Activity\n" +
"\n" +
"Investigate the Growth of Leaf Yeast\n" +
"\n" +
"Three sterile malt agar plates.\n" +
"Plate 1: control – keep closed and place upside down.\n" +
"Plate 2: remove lid and place base upside down to prevent its contamination.\n" +
"Put a ridge of petroleum jelly on the inside of the lid.\n" +
"Place an ash leaflet with its upper side stuck to the petroleum jelly.\n" +
"Lift the base of the plate onto the lid and set the plate with the lid on top for a day.\n" +
"Seal the lid to the base with tape.\n" +
"After a day turn the plate upside down and incubate.\n" +
"Plate 3: repeat as for plate 2 but the lower side of the leaflet is in contact with the jelly.\n" +
"Results:\n" +
"Control Plate: must be clear, without any growth of micro-organisms, in order to continue.\n" +
"Experimental Plates: pink shiny pimples are colonies of yeast.\n" +
"Compare exposed upper and lower leaf surfaces for yeast distribution.\n" +
"\n" +
"Precautions\n" +
"\n" +
"Laboratory Procedures When Handling Micro-organisms\n" +
"\n" +
"Assume all micro-organisms are harmful.\n" +
"Swab the laboratory bench with disinfectant t before and after the experiment.\n" +
"Wash your hands before and after with a disinfectant soap.\n" +
"Sterilise all equipment, in a pressure cooker, before and after the experiment.\n" +
"Sterilise the tip of scissors and forceps by flaming immediately before and after use.\n" +
"Label each plate on its base with an indelible marker pen.\n" +
"View the incubated plates through the clear lid - never remove the lid.\n" +
"Sterile all cultures in a pressure cooker before disposal.\n" +
"Never put anything near or into your mouth in the laboratory.\n" +
"Never handle items that may have come in contact with cultured micro-organisms.\n" +
"Sterility: treated so that there are no living micro-organisms.\n" +
"\n" +
"Asepsis: methods of preventing contamination by unwanted micro-organisms.");

    }//GEN-LAST:event_fungActionPerformed

    private void virusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virusActionPerformed
        // TODO add your handling code here:
                jTextArea1.setText("Viruses \n" +
"\n" +
"Characteristics\n" +
"\n" +
"Infectious agent\n" +
"Non-cellular\n" +
"Tiny – 30,000 in single file across one millimetre on average\n" +
"Obligate intracellular parasites\n" +
"No metabolic activity external to their host cell\n" +
"Multiply only within their host cell\n" +
"No enzyme activity if not in contact with the host cell\n" +
"Organic: composed of hereditary material (DNA or RNA) is surrounded by a protein coat\n" +
"Hereditary material replicated and transcribed within host cell\n" +
"Living or non-living?\n" +
"\n" +
"Structure \n" +
"\n" +
"Textbook Diagram: look at the outline structure of virus.\n" +
"\n" +
"Textbook Diagram: look at the variety of virus shapes.\n" +
"\n" +
"\n" +
"Economic Importance \n" +
"Cause disease of Livestock and Animal Pets: foot and mouth, rabies\n" +
"Crop Diseases: mosaic disease of tobacco, potato and tomato\n" +
"\n" +
"Medical Importance\n" +
"Human Diseases: common cold, measles, AIDS, flu, measles, chicken pox, hepatitis\n" +
"Cancer: some cancers are caused by viruses\n" +
"\n" +
"Uses of Viruses\n" +
"Vaccine: cowpox used against smallpox\n" +
"Genetic Engineering: viruses are used to insert ‘foreign’ DNA into the target cell’s DNA\n" +
"Biological Control: keep rabbit population in check\n" +
"\n" +
"Reproduction of Viruses \n" +
"Attachment: the virus comes in contact with the host cell and sticks to its surface\n" +
"Penetration: the viral hereditary material or the entire virus enters the host cell\n" +
"Replication: the viral hereditary material is released from the protein, the viral hereditary material redirects the host cell’s metabolism to make many copies of the viral hereditary material and viral proteins\n" +
"Assembly: viral hereditary material and proteins come together forming new viruses\n" +
"Release: new viruses pass to the outside by bursting of host cell or by ‘budding’\n" +
"Most viruses cannot survive for long outside their host cell.\n" +
"\n" +
"Transfer to host cells is purely by chance – viruses do not actively search for new host cells.\n" +
"\n" +
"Antibiotics do not have any effect on viruses.");

    }//GEN-LAST:event_virusActionPerformed

    private void amoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amoeActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("Amoeba - A member of the Protoctista (Protista)  \n" +
"\n" +
"Amoeba Characteristics\n" +
"\n" +
"Unicellular, eukaryote, no cell wall.\n" +
"Reproduction: binary fission.\n" +
"Movement: use of pseudopodia.\n" +
"Feeding: phagocytosis — similar to our phagocytic white blood cells.\n" +
"\n" +
"Amoeba Structure\n" +
"\n" +
"Textbook Diagram: typical structure of an Amoeba cell.\n" +
"\n" +
"Cytoplasm\n" +
"\n" +
"Ectoplasm: jelly-like outer layer of cytoplasm next to the cell membrane.\n" +
"- restricts the entry of water by osmosis\n" +
"- supports and strengthens the cell\n" +
"Endoplasm: liquid inner cytoplasm in which the organelles are suspended.\n" +
"\n" +
"Functions of Some Cell Parts  \n" +
"\n" +
"Food Vacuoles\n" +
"\n" +
"Solid food ingested by phagocytosis is digested in the food vacuoles.\n" +
"Products of digestion pass form the food vacuole into the cytoplasm.\n" +
"Indigestible material is egested at the cell membrane.\n" +
"Contractile Vacuole\n" +
"\n" +
"Active expulsion of the excess water that enters Amoeba by osmosis.\n" +
"Maintains cytoplasm at the correct concentration — osmoregulation.\n" +
"Pseudopods\n" +
"\n" +
"Temporary narrow extensions of the cell for locomotion and food capture.\n" +
"Amoeba makes movement responses to external stimuli such as light and chemicals.");

    }//GEN-LAST:event_amoeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OOrgNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OOrgNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OOrgNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OOrgNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OOrgNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amoe;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton bck;
    private javax.swing.JButton fung;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton kingdoms;
    private javax.swing.JLabel textlabel;
    private javax.swing.JButton virus;
    // End of variables declaration//GEN-END:variables
}
