/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author Laura Nesbitt
 */
public class SHigherlvl extends javax.swing.JFrame {

    /**
     * Creates new form Higherlvl
     */
    public SHigherlvl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        papers14btn = new javax.swing.JButton();
        papers13btn = new javax.swing.JButton();
        papers11btn = new javax.swing.JButton();
        papers12btn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Higher Level");

        papers14btn.setBackground(new java.awt.Color(255, 153, 0));
        papers14btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        papers14btn.setText("2014");
        papers14btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papers14btnActionPerformed(evt);
            }
        });

        papers13btn.setBackground(new java.awt.Color(255, 153, 0));
        papers13btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        papers13btn.setText("2013");
        papers13btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papers13btnActionPerformed(evt);
            }
        });

        papers11btn.setBackground(new java.awt.Color(255, 153, 0));
        papers11btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        papers11btn.setText("2011");
        papers11btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papers11btnActionPerformed(evt);
            }
        });

        papers12btn.setBackground(new java.awt.Color(255, 153, 0));
        papers12btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        papers12btn.setText("2012");
        papers12btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papers12btnActionPerformed(evt);
            }
        });

        Backbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Backbtn)
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(papers14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(papers13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(papers12btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(papers11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Backbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papers13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(papers14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(papers12btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(papers11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // return to previous section
        SFrame2 myFrame2 = new SFrame2();
        myFrame2.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void papers14btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papers14btnActionPerformed
        // Opens the 2014 higher level papers in default browser

        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2014/LC025ALP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_papers14btnActionPerformed

    private void papers13btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papers13btnActionPerformed
        // Opens the 2013 higher level papers in default browser
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2013/LC025ALP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_papers13btnActionPerformed

    private void papers12btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papers12btnActionPerformed
        // Opens the 2012 higher level papers in default browser
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2012/LC025ALP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_papers12btnActionPerformed

    private void papers11btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papers11btnActionPerformed
        // Opens the 2011 higher level papers in default browser
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2011/LC025ALP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_papers11btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHigherlvl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SHigherlvl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton papers11btn;
    private javax.swing.JButton papers12btn;
    private javax.swing.JButton papers13btn;
    private javax.swing.JButton papers14btn;
    // End of variables declaration//GEN-END:variables
}
