/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

/**
 *
 * @author Laura Nesbitt
 */
public class SMarking extends javax.swing.JFrame {

    /**
     * Creates new form Marking
     */
    public SMarking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarkingLabel = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        Highbtn = new javax.swing.JButton();
        Ordbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MarkingLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MarkingLabel.setText("Marking Scheme");

        Backbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Highbtn.setBackground(new java.awt.Color(255, 153, 0));
        Highbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Highbtn.setText("Higher Level");
        Highbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighbtnActionPerformed(evt);
            }
        });

        Ordbtn.setBackground(new java.awt.Color(255, 153, 0));
        Ordbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ordbtn.setText("Ordinary Level");
        Ordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(MarkingLabel)
                .addGap(157, 157, 157))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Highbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ordbtn)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MarkingLabel)
                    .addComponent(Backbtn))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Highbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // return to previous section
        SGUI myGUI = new SGUI();
        myGUI.setVisible(true);
        dispose();

    }//GEN-LAST:event_BackbtnActionPerformed

    private void HighbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighbtnActionPerformed
        // Opens the higher marking scheme section
        SHighermarking myHighermarking = new SHighermarking();
        myHighermarking.setVisible(true);
        dispose();
    }//GEN-LAST:event_HighbtnActionPerformed

    private void OrdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdbtnActionPerformed
        // Opens the lower marking scheme section
        SOrdinarymarking myOrdinarymarking = new SOrdinarymarking();
        myOrdinarymarking.setVisible(true);
        dispose();
    }//GEN-LAST:event_OrdbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMarking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SMarking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Highbtn;
    private javax.swing.JLabel MarkingLabel;
    private javax.swing.JButton Ordbtn;
    // End of variables declaration//GEN-END:variables
}
