/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author Laura Nesbitt
 */
public class SNotes extends javax.swing.JFrame {

    /**
     * Creates new form Notes
     */
    public SNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        Noteslbl = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        Methodbtn = new javax.swing.JButton();
        Ecologybtn = new javax.swing.JButton();
        Nutritionbtn = new javax.swing.JButton();
        Ecobtn = new javax.swing.JButton();
        Studybtn = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Noteslbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Noteslbl.setText("Notes");

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Methodbtn.setBackground(new java.awt.Color(255, 153, 0));
        Methodbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Methodbtn.setText("Scientific method");
        Methodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MethodbtnActionPerformed(evt);
            }
        });

        Ecologybtn.setBackground(new java.awt.Color(255, 153, 0));
        Ecologybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ecologybtn.setText("Ecology");
        Ecologybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcologybtnActionPerformed(evt);
            }
        });

        Nutritionbtn.setBackground(new java.awt.Color(255, 153, 0));
        Nutritionbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nutritionbtn.setText("Nutrition");
        Nutritionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NutritionbtnActionPerformed(evt);
            }
        });

        Ecobtn.setBackground(new java.awt.Color(255, 153, 0));
        Ecobtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ecobtn.setText("Ecosystem");
        Ecobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EcobtnActionPerformed(evt);
            }
        });

        Studybtn.setBackground(new java.awt.Color(255, 153, 0));
        Studybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Studybtn.setText("Study Log");
        Studybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Methodbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ecologybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ecobtn, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(Nutritionbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Backbtn)
                .addGap(116, 116, 116)
                .addComponent(Noteslbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Studybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Noteslbl)
                    .addComponent(Backbtn))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Methodbtn)
                    .addComponent(Nutritionbtn))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ecologybtn)
                    .addComponent(Ecobtn))
                .addGap(37, 37, 37)
                .addComponent(Studybtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // return to the previous section

        SGUI myGUI = new SGUI();
        myGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void MethodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MethodbtnActionPerformed
        // opens notes on the scientific method in default browser 
        try {
            Desktop.getDesktop().browse(new URL("http://www.skoool.ie/skoool/examcentre_sc.asp?id=2841").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_MethodbtnActionPerformed

    private void EcologybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcologybtnActionPerformed
        // opens notes on Ecology in default browser 
        try {
            Desktop.getDesktop().browse(new URL("http://www.skoool.ie/skoool/examcentre_sc.asp?id=2898").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_EcologybtnActionPerformed

    private void NutritionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NutritionbtnActionPerformed
        // opens notes on Nutrition in default browser 
        try {
            Desktop.getDesktop().browse(new URL("http://www.skoool.ie/skoool/examcentre_sc.asp?id=2843").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_NutritionbtnActionPerformed

    private void EcobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EcobtnActionPerformed
        // opens notes on Ecology in default browser 
        try {
            Desktop.getDesktop().browse(new URL("http://www.skoool.ie/skoool/examcentre_sc.asp?id=2883").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_EcobtnActionPerformed

    private void StudybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudybtnActionPerformed
        // OPens the study log
        SStudy myStudy = new SStudy();
        myStudy.setVisible(true);
        dispose();
    }//GEN-LAST:event_StudybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Ecobtn;
    private javax.swing.JButton Ecologybtn;
    private javax.swing.JButton Methodbtn;
    private javax.swing.JLabel Noteslbl;
    private javax.swing.JButton Nutritionbtn;
    private javax.swing.JButton Studybtn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    // End of variables declaration//GEN-END:variables

}
