/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author Laura Nesbitt
 */
public class SOrdinarymarking extends javax.swing.JFrame {

    /**
     * Creates new form Ordinarymarking
     */
    public SOrdinarymarking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        Omarking14btn = new javax.swing.JButton();
        Omarking11btn = new javax.swing.JButton();
        Omarking13btn = new javax.swing.JButton();
        Omarkingbtn12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ordinary Marking Scheme");

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Omarking14btn.setBackground(new java.awt.Color(255, 153, 0));
        Omarking14btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Omarking14btn.setText("2014");
        Omarking14btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Omarking14btnActionPerformed(evt);
            }
        });

        Omarking11btn.setBackground(new java.awt.Color(255, 153, 0));
        Omarking11btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Omarking11btn.setText("2011");
        Omarking11btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Omarking11btnActionPerformed(evt);
            }
        });

        Omarking13btn.setBackground(new java.awt.Color(255, 153, 0));
        Omarking13btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Omarking13btn.setText("2013");
        Omarking13btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Omarking13btnActionPerformed(evt);
            }
        });

        Omarkingbtn12.setBackground(new java.awt.Color(255, 153, 0));
        Omarkingbtn12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Omarkingbtn12.setText("2012");
        Omarkingbtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Omarkingbtn12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Backbtn)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)
                        .addContainerGap(85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Omarking14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Omarkingbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Omarking11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Omarking13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Backbtn))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Omarking14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Omarking13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Omarking11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Omarkingbtn12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Omarking13btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Omarking13btnActionPerformed
        // brings you to the 2013 marking scheme 
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/markingschemes/2013/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Omarking13btnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // brings you to the previous section
        SMarking myMarking = new SMarking();
        myMarking.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void Omarking14btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Omarking14btnActionPerformed
        // brings you to the 2014 marking scheme 
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/markingschemes/2014/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Omarking14btnActionPerformed

    private void Omarkingbtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Omarkingbtn12ActionPerformed
        // brings you to the 2012 marking scheme 
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/markingschemes/2012/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Omarkingbtn12ActionPerformed

    private void Omarking11btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Omarking11btnActionPerformed
        // brings you to the 2011 marking scheme 
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/markingschemes/2011/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Omarking11btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SOrdinarymarking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SOrdinarymarking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Omarking11btn;
    private javax.swing.JButton Omarking13btn;
    private javax.swing.JButton Omarking14btn;
    private javax.swing.JButton Omarkingbtn12;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
