/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biology;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author Laura Nesbitt
 */
public class SOrdinarylvl extends javax.swing.JFrame {

    /**
     * Creates new form Ordinarylvl
     */
    public SOrdinarylvl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        Opaper14btn = new javax.swing.JButton();
        Opaper12btn = new javax.swing.JButton();
        Opaper13btn = new javax.swing.JButton();
        Opaper11btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ordinary Level");

        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Opaper14btn.setBackground(new java.awt.Color(255, 153, 0));
        Opaper14btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Opaper14btn.setText("2014");
        Opaper14btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opaper14btnActionPerformed(evt);
            }
        });

        Opaper12btn.setBackground(new java.awt.Color(255, 153, 0));
        Opaper12btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Opaper12btn.setText("2012");
        Opaper12btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opaper12btnActionPerformed(evt);
            }
        });

        Opaper13btn.setBackground(new java.awt.Color(255, 153, 0));
        Opaper13btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Opaper13btn.setText("2013");
        Opaper13btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opaper13btnActionPerformed(evt);
            }
        });

        Opaper11btn.setBackground(new java.awt.Color(255, 153, 0));
        Opaper11btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Opaper11btn.setText("2011");
        Opaper11btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opaper11btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Backbtn)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Opaper14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addComponent(Opaper13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Opaper12btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Opaper11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Backbtn))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opaper14btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opaper13btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Opaper12btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Opaper11btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        //brings you to the previous section
        SFrame2 myFrame2 = new SFrame2();
        myFrame2.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    private void Opaper14btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opaper14btnActionPerformed
        // opens the 2014 paper in default browser
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2014/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Opaper14btnActionPerformed

    private void Opaper13btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opaper13btnActionPerformed
        // opens the 2013 paper in default browser
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2013/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Opaper13btnActionPerformed

    private void Opaper12btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opaper12btnActionPerformed
        // opens the 2012 paper in default browser
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2012/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Opaper12btnActionPerformed

    private void Opaper11btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opaper11btnActionPerformed
        // opens the 2011 paper in default browser
        try {
            Desktop.getDesktop().browse(new URL("http://examinations.ie/archive/exampapers/2011/LC025GLP000EV.pdf").toURI());
        } catch (URISyntaxException | IOException e) {
        }
    }//GEN-LAST:event_Opaper11btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SOrdinarylvl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SOrdinarylvl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Opaper11btn;
    private javax.swing.JButton Opaper12btn;
    private javax.swing.JButton Opaper13btn;
    private javax.swing.JButton Opaper14btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
