package Biology;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Laura Nesbitt
 */
public class SStudy extends javax.swing.JFrame {
//declare 

    private ArrayList<SStudyLog> aList;
    private String Name, Day, Start, Finish;
    private int count;

    SStudyLog[] arr;
    private int i;

    /**
     * Creates new form Study
     */
    public SStudy() {
        initComponents();

        arr = new SStudyLog[3];

        aList = new ArrayList<>();
        Name = new String();
        Day = new String();
        Start = new String();
        Finish = new String();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nametf = new javax.swing.JTextField();
        Daytf = new javax.swing.JTextField();
        Starttf = new javax.swing.JTextField();
        Finishtf = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();
        Displaybtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Study Log");

        Backbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Name of subject:");

        jLabel3.setText("Day studied:");

        jLabel4.setText("Time starting:");

        jLabel5.setText("Time finishing:");

        Nametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NametfActionPerformed(evt);
            }
        });

        Starttf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarttfActionPerformed(evt);
            }
        });

        Addbtn.setBackground(new java.awt.Color(255, 153, 0));
        Addbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        Displaybtn.setBackground(new java.awt.Color(255, 153, 0));
        Displaybtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Displaybtn.setText("Display all");
        Displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Addbtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Displaybtn)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Finishtf, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Starttf)
                                        .addGap(23, 23, 23))
                                    .addComponent(Daytf)
                                    .addComponent(Nametf)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Backbtn)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel1))
                            .addComponent(jLabel5))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Backbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Daytf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Starttf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Finishtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addbtn)
                    .addComponent(Displaybtn))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StarttfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarttfActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_StarttfActionPerformed

    private void NametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NametfActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NametfActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // add objects to a file
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        SStudyLog a;
        a = new SStudyLog();

// TODO add your handling code here:
        Name = Nametf.getText();
        Day = Daytf.getText();
        Start = Starttf.getText();
        Finish = Finishtf.getText();
        try {
            outFile = new File("StudyLog.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(Name);
            bw.newLine();
            bw.write(Day);
            bw.newLine();
            bw.write(Start);
            bw.newLine();
            bw.write(Finish);
            bw.newLine();

            bw.close();
            JOptionPane.showMessageDialog(null, "successfully writen to file ");
        } catch (IOException e) {
            System.out.println(" Error writing to file " + e);
        }
    }//GEN-LAST:event_AddbtnActionPerformed

    @SuppressWarnings("empty-statement")
    private void DisplaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaybtnActionPerformed
        // read from a file
        String Name;
        String Day;
        String Start;
        String Finish;
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("StudyLog.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            Name = br.readLine();
            Day = br.readLine();
            Start = br.readLine();
            Finish = br.readLine();
            while (Name != null) {

                JOptionPane.showMessageDialog(null, " Name : " + Name + " \n Day : " + Day + " \n Start: " + Start + " \n Finish: " + Finish);

                Name = br.readLine();
                Day = br.readLine();
                Start = br.readLine();
                Finish = br.readLine();
            }
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_DisplaybtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // Return to the notes section of app
        SNotes myNotes = new SNotes();
        myNotes.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SStudy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField Daytf;
    private javax.swing.JButton Displaybtn;
    private javax.swing.JTextField Finishtf;
    private javax.swing.JTextField Nametf;
    private javax.swing.JTextField Starttf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    private static class study {

        public study() {
        }

    }
}
